import json 
import io 
import csv
from google.genai import types

from app.models.models import ConstraintInput

def to_csv_string(regional):
    headers = regional[0].keys()
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=headers)
    writer.writeheader()
    
    for row in regional: 
        writer.writerow(row)
    return buffer.getvalue()
    
def call_gemini(constraints: ConstraintInput, regional_list: list, gemini):
    prompt = f"""You are an expert dietitian specializing in creating therapeutic diets that adhere to specific health conditions (e.g., inflammation, RA) and dietary restrictions (e.g., vegan, vegetarian). Your primary objective is to fulfill the patient's daily macronutrient needs (calories, carbohydrates, fats, proteins, and fibre) based on their specific fitness goals.

        ### Core Task: Meal Plan Generation
        You will be provided with a CSV list of available food items (regional and global). You must generate 3 distinct daily meal plans based on the user's profile and constraints.

        ### Ingredient Data Format
        All nutrient values (protein, carbs, fat, calories, fibre) in the provided list are PER 100 GRAMS of the food item. When you specify an `amount` for an ingredient in your output, it must be in GRAMS — this amount will be used to scale the per-100g values (actual contribution = value * amount / 100) to compute real macro totals. Choose amounts that are realistic serving sizes and that cause the plan to hit the daily targets once scaled.

        ### Guidelines & Rules
        1. STRICT INGREDIENT USAGE: Use ONLY ingredients from the provided list, referenced by their exact `id`. Do NOT invent or hallucinate food items or ids.
        2. MUST-HAVE FOODS: Attempt to include the client's "must-have" foods. If it is impossible or unviable to include them based on macros or availability, skip them and list them in the `skipped_items` array.
        3. REFERENCING: Reference each ingredient ONLY by its exact `id` from the provided list, mapped as `id` in your output. Do not output ingredient names, macros, or any other fields.
        4. TARGETS & VARIETY: Each of the 3 plans must independently hit the daily calorie and macro targets once amounts are scaled per the formula above. Ensure the plans are as diverse from each other as possible.
        5. MICRO-NUTRIENTS: Since micro-nutrient data is absent, approximate completeness by ensuring a wide variety of meals and ingredients across the plans.
        6. PLAN-NAMING: Each plan should be given a name appropriate to the plan's contents, nutritional amounts.
        
        LASTLY AND VERY IMPORTANTLY: Make sure that each of the macro-nutrient targets (generated by you, given the constraints) is accurately COMPLETED (including calories, protein, carbs, fats) by scaling 
        the ingredient amounts appropriately or having a multitude of meals.
        
        
        ### User Constraints
        - Fitness goals: {constraints.fitness_goals}
        - Age: {constraints.age} years
        - Biological Sex: {constraints.sex}
        - Height: {constraints.height} cm
        - Weight: {constraints.weight} kg
        - Activity level: {constraints.activity_level}
        - Health conditions: {', '.join(constraints.health_conditions)}
        - Must include: {', '.join(constraints.required_food_items)}
        - Dietary restrictions: {', '.join(constraints.dietary_restrictions)}

        ### Available Ingredients (CSV: id,name,protein,carbs,fat,calories,fibre — all values per 100g)
        {to_csv_string(regional_list)}

        ### Output Format
        Return ONLY a valid JSON object. Do not include markdown formatting, do not include any other text, and do not provide explanations. Each ingredient entry must contain ONLY `foodID` and `amount` (grams) — no other fields. Use the exact schema below:

        {{
        "skipped_items": ["item1", "item2"],
        "plans": [
            {{
            "name": "Plan 1",
            "meals": [
                {{
                "name": "Breakfast",
                "ingredients": [
                    {{
                    "id": 0,
                    "amount": 0
                    }}
                ]
                }}
            ]
            }}
        ]
        }}
        """
        
    print(f"PROMPT LENGTH: {len(prompt)} chars, {len(regional_list)} food items")

    import time
    start = time.time()
    response = gemini.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt,
        # config=types.GenerateContentConfig(
        # thinking_config=types.ThinkingConfig(thinking_level="high")
        # )
    )
    print(f"GEMINI CALL TOOK: {time.time() - start:.2f}s")


    try:
        return json.loads(response.text)
    except json.JSONDecodeError:
        cleaned = response.text.strip().removeprefix("```json").removesuffix("```").strip()
        return json.loads(cleaned)
    

    